spring:
  application:
    name: langchain4j
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
langchain4j:
  open-ai:
    streaming-chat-model:
      api-key: ${langchain4j.open-ai.embedding-model.api-key}
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 0.7
      timeout: PT60S
      log-requests: true
      log-responses: true
    embedding-model:
      api-key: ${langchain4j.open-ai.embedding-model.api-key}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v4
      timeout: PT30S
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10
  community:
    redis:
      host: localhost
      port: 6379